---
  - src: geerlingguy.apache
    version: 1.7.2
  - src: geerlingguy.mysql
    version: 2.2.1
  - src: geerlingguy.php
    version: 3.0.4
  - src: geerlingguy.php-mysql
    version: 2.0.0
  - src: geerlingguy.phpmyadmin
    version: 1.2.0
  - src: geerlingguy.composer
    version: 1.4.0
  - src: ssachtleben.apache-mcrypt
    version: master