---
  - src: geerlingguy.apache
  - src: geerlingguy.mysql
  - src: geerlingguy.php
  - src: geerlingguy.phpmyadmin
  - src: geerlingguy.nodejs
  - src: geerlingguy.composer
  - src: ssachtleben.apache-mcrypt