---
  - src: geerlingguy.nginx
    version: 1.9.5
  - src: geerlingguy.mysql
    version: 2.2.1
  - src: geerlingguy.php
    version: 3.3.0
  - src: geerlingguy.php-mysql
    version: 2.0.0
  - src: geerlingguy.composer
    version: 1.5.0
